
import Card from "@/components/Card";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Creando componentes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main>
        <Card/>
      </main>
    </>
  );
}
